name: Publish package
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '**.scss'
      - '**.css'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Fetch code
    - run: make install
    - run: make build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 # Add .npmrc for scoped package
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@oslokommune' # Defaults to the user or organization that owns the workflow file
    - run: make install
    - run: make build
    - run: make publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # Fetch code
      with:
        ref: ${{ github.ref }}
    - name: "Automated Version Bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
