name: Publish package
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '**.scss'
      - '**.css'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # Fetch code
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v1 # Add .npmrc for scoped package
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@tuuturu' # Defaults to the user or organization that owns the workflow file
    - run: npm install
    - run: npm run build

    - name: "Automated Version Bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
